import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "next/font/google";
import { NextUIProvider } from "@nextui-org/system";

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
});

// const brico = Bricolage_Grotesque({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-brico",
// });

export const metadata: Metadata = {
  title: "Ankh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.className} `}>
      <body>
        <NextUIProvider>{children}</NextUIProvider>
      </body>
    </html>
  );
}
